# Generated by Django 5.0.3 on 2024-04-09 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_order_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='GelenArama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=11)),
                ('aciklama', models.TextField()),
                ('arama_nedeni', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sirket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('web', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.CreateModel(
            name='KisiRehberi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('sirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sirket')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
